version: "3.7"
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: weather
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes: 
  postgres: